In [1]:
import torch
from torch_geometric.datasets import Amazon, ZINC, NeuroGraphDataset, TUDataset,PPI
from dotenv import load_dotenv
import os

In [13]:
from torch_geometric.utils import erdos_renyi_graph,get_laplacian,to_dense_adj

er_graph=erdos_renyi_graph(num_nodes=10,edge_prob=0.5)
er_graph

tensor([[0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5,
         5, 5, 5, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9],
        [4, 8, 2, 3, 4, 5, 7, 1, 4, 5, 6, 7, 9, 1, 7, 8, 9, 0, 1, 2, 7, 1, 2, 6,
         7, 8, 9, 2, 5, 1, 2, 3, 4, 5, 8, 9, 0, 3, 5, 7, 9, 2, 3, 5, 7, 8]])

In [14]:
er_lap,weight=get_laplacian(er_graph)

In [15]:
adj_matrix=to_dense_adj(er_lap,edge_attr=weight)
adj_matrix

tensor([[[ 2.,  0.,  0.,  0., -1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  5., -1., -1., -1., -1.,  0., -1.,  0.,  0.],
         [ 0., -1.,  6.,  0., -1., -1., -1., -1.,  0., -1.],
         [ 0., -1.,  0.,  4.,  0.,  0.,  0., -1., -1., -1.],
         [-1., -1., -1.,  0.,  4.,  0.,  0., -1.,  0.,  0.],
         [ 0., -1., -1.,  0.,  0.,  6., -1., -1., -1., -1.],
         [ 0.,  0., -1.,  0.,  0., -1.,  2.,  0.,  0.,  0.],
         [ 0., -1., -1., -1., -1., -1.,  0.,  7., -1., -1.],
         [-1.,  0.,  0., -1.,  0., -1.,  0., -1.,  5., -1.],
         [ 0.,  0., -1., -1.,  0., -1.,  0., -1., -1.,  5.]]])

In [16]:
import torch
eigen_values,vecs=torch.linalg.eig(adj_matrix)

In [18]:
vecs.real

tensor([[[-0.3162,  0.6849,  0.5472,  0.1978, -0.0562,  0.1646, -0.2389,
           0.0534,  0.0461, -0.0091],
         [-0.3162, -0.0297, -0.1947, -0.3666, -0.2387,  0.6378, -0.0211,
          -0.0294, -0.4352,  0.2691],
         [-0.3162, -0.1545, -0.0035, -0.2388,  0.2411,  0.0320, -0.3059,
          -0.2379, -0.0909, -0.7756],
         [-0.3162,  0.0235, -0.4056,  0.2878, -0.7078, -0.1695, -0.1376,
          -0.1614,  0.2532, -0.1154],
         [-0.3162,  0.1983,  0.0804, -0.6563, -0.0453, -0.5363,  0.2427,
          -0.1637,  0.0939,  0.1983],
         [-0.3162, -0.1650, -0.0451,  0.0457,  0.3419,  0.3649,  0.1267,
          -0.2369,  0.7091,  0.2089],
         [-0.3162, -0.6458,  0.6052,  0.1525, -0.2214, -0.1129,  0.0454,
           0.0773, -0.1113,  0.1059],
         [-0.3162, -0.0060, -0.1947, -0.0740,  0.0825, -0.0208,  0.0941,
           0.8926,  0.1464, -0.1496],
         [-0.3162,  0.1405, -0.1243,  0.4057,  0.1933, -0.0427,  0.6994,
          -0.1648, -0.3497, -0.1494],
 

In [24]:
eigen_values.real

tensor([[3.5763e-07, 8.0999e-01, 1.0542e+00, 3.4149e+00, 8.3479e+00, 5.7284e+00,
         7.5452e+00, 7.2625e+00, 4.8370e+00, 5.0000e+00]])

In [2]:
load_dotenv('.env')
amazon_path = os.getenv('Amazon')
hiv_path = os.getenv('HIV')
tox21_path = os.getenv("Tox21")
neuro_path = os.getenv("NeuroGraph")
protein_path = os.getenv("Proteins")
reddit_path=os.getenv("Reddit")
zinc_path=os.getenv("Zinc")
print(reddit_path)

/Volumes/Vault/Smudge/Datasets/Capstone_1/Reddit/


In [3]:
dataset = Amazon(root=amazon_path,name='Computers')

/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/data/dataset.py:238: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  if osp.exists(f) an

In [4]:
data=dataset[0]
data

Data(x=[13752, 767], edge_index=[2, 491722], y=[13752])

In [8]:
dataset=PPI(root=protein_path,split='train')

/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/data/dataset.py:238: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  if osp.exists(f) an

In [14]:
train=dataset[2]
train.num_features

50

In [15]:
train

Data(x=[2263, 50], edge_index=[2, 59644], y=[2263, 121])

In [3]:
dataset = ZINC(root=zinc_path,split='train')

/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/data/dataset.py:238: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  if osp.exists(f) an

In [4]:
dataset.num_features

1

In [11]:
dataset[0].ed

Data(x=[19, 9], edge_index=[2, 40], edge_attr=[40, 3], smiles='CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)=[O+]2', y=[1, 1])

In [19]:
from sklearn.model_selection import train_test_split
from torch_geometric.data import DataLoader
params={
    'batch_size':8,
    'shuffle':True,
    'num_workers':0
}
dataset = dataset.shuffle()
train_ratio = 0.75
val_ratio = 0.15
test_ratio = 0.10
train_set, test_set = train_test_split(
        dataset, test_size=1-train_ratio)
val_set, test_set = train_test_split(
        test_set, test_size=test_ratio/(test_ratio+val_ratio))

# Loaders
train_loader = DataLoader(train_set, **params)
test_loader = DataLoader(test_set, **params)
val_loader = DataLoader(val_set, **params)

/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [21]:
for data in train_loader:
    print(data)

DataBatch(x=[180, 9], edge_index=[2, 402], edge_attr=[402, 3], smiles=[8], y=[8, 1], batch=[180], ptr=[9])
DataBatch(x=[190, 9], edge_index=[2, 400], edge_attr=[400, 3], smiles=[8], y=[8, 1], batch=[190], ptr=[9])
DataBatch(x=[287, 9], edge_index=[2, 634], edge_attr=[634, 3], smiles=[8], y=[8, 1], batch=[287], ptr=[9])
DataBatch(x=[177, 9], edge_index=[2, 380], edge_attr=[380, 3], smiles=[8], y=[8, 1], batch=[177], ptr=[9])
DataBatch(x=[172, 9], edge_index=[2, 366], edge_attr=[366, 3], smiles=[8], y=[8, 1], batch=[172], ptr=[9])
DataBatch(x=[142, 9], edge_index=[2, 298], edge_attr=[298, 3], smiles=[8], y=[8, 1], batch=[142], ptr=[9])
DataBatch(x=[222, 9], edge_index=[2, 488], edge_attr=[488, 3], smiles=[8], y=[8, 1], batch=[222], ptr=[9])
DataBatch(x=[211, 9], edge_index=[2, 450], edge_attr=[450, 3], smiles=[8], y=[8, 1], batch=[211], ptr=[9])
DataBatch(x=[237, 9], edge_index=[2, 498], edge_attr=[498, 3], smiles=[8], y=[8, 1], batch=[237], ptr=[9])
DataBatch(x=[184, 9], edge_index=[2, 

In [3]:
zinc_path=os.getenv("Zinc")
dataset = ZINC(root=zinc_path,subset=False)

Extracting /Volumes/Vault/Smudge/Datasets/Capstone_1/Zinc/molecules.zip
Processing...
Processing test dataset: 100%|██████████| 5000/5000 [00:00<00:00, 26003.22it/s]
Done!
/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/io/fs.py:215: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use

In [5]:
dataset = NeuroGraphDataset(root=neuro_path,name='HCPGender')

Processing...
/Users/smudge/Desktop/Code/capstone/.venv/lib/python3.12/site-packages/torch_geometric/datasets/neurograph.py:113: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.


In [7]:
dataset[0]

Data(x=[1000, 1000], edge_index=[2, 47450], y=[1])

In [1]:
import torch
from torch_geometric.data import Data

def flip_edges(data: Data) -> Data:
    """Flips the edges of a PyTorch Geometric Data object."""

    # Flip the edge indices
    flipped_edge_index = data.edge_index.flip(dims=[0])

    # Create a new Data object with the flipped edges
    flipped_data = Data(x=data.x, edge_index=flipped_edge_index, edge_attr=data.edge_attr)

    return flipped_data

# Create a sample graph
edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)
data = Data(x=x, edge_index=edge_index)

# Flip the edges
flipped_data = flip_edges(data)


In [2]:

print("Original edge_index:")
print(data.edge_index)
print("Flipped edge_index:")
print(flipped_data.edge_index)

Original edge_index:
tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])
Flipped edge_index:
tensor([[1, 0, 2, 1],
        [0, 1, 1, 2]])


In [5]:
x = torch.randn(3, 2)
y = torch.zeros(3, 2)

a=torch.where(x>y,1,0)

In [6]:
a

tensor([[1, 1],
        [0, 1],
        [1, 0]])

In [10]:
import torch
import math
torch.sin(torch.tensor(math.pi/4))

tensor(0.7071)

In [12]:
1/math.sqrt(2)

0.7071067811865475